### ISSUE TITLE
Provide access to the response body for etag generation

### ISSUE THREAD

**Issue by brentsnook** [seancribbs/webmachine-ruby#169]
I'm messing about with generating etags on a resource that has multiple representations. I'd like the etag to be a hash of the content for whichever content type is requested (in this case, JSON or PDF).

I'd love to be able to get at the response body content within my resource in order to generate my etag but unfortunately it is only set at o18:

https://github.com/seancribbs/webmachine-ruby/blob/master/lib/webmachine/decision/flow.rb#L472

What I'm after is some way of generating the body lazily and exposing it from the resource so that I can use it much earlier for my etag generation. Any ideas around how to do this? I can have a go at a pull request if this makes sense.

**Comment by bethesque** [comment]
Hey @brentsnook, closing this, but interested to hear how you solved the problem (for future reference).

**Comment by brentsnook** [comment]
Hey @bethesque! From memory I think we were planning to do what I mentioned before (hash service version with record modification time) but I don't think we got around to it in the end - it was a while ago.
