### ISSUE TITLE
PUT method calling from_json although resource doesn't exist

### ISSUE THREAD

**Issue by kgish** [seancribbs/webmachine-ruby#207]
For some reason PUT is still hitting the `from_json` method although the `resource_exists?` method returns a big bad `false`, any reason I still see the following?
```
[2014-12-29 22:02:49] INFO  WEBrick 1.3.1
[2014-12-29 22:02:49] INFO  ruby 2.1.5 (2014-11-13) [x86_64-linux]
[2014-12-29 22:02:49] INFO  Webmachine::Adapters::WEBrick::Server#start: pid=1679 \
  port=8080
ProductResource: resource_exists => false
ProductResource: from_json => PUT
localhost - - [29/Dec/2014:22:02:51 CET] "PUT /products/25 HTTP/1.1" 204 0
- -> /products/25
```

**Comment by bethesque** [comment]
Closeable?

**Comment by shardnit** [comment]
Perhaps, add a comment to the PUT example document. Hours after investigating, when `resource_exists?` not returning 404 for a PUT on non-available resource, I realized that I need to handle it in `is_conflict?` callback. In that sense, `resource_available?` callback returning true or false doesnt make any difference to PUT requests.

**Comment by bethesque** [comment]
My head is a bit out of this space, but happy to update the docs. Something like "Note that the return value of resource_exists? does not affect the decision flow for PUT. If you wish to disallow PUT to a resource that does not already exist, then return true from `is_conflict?`

**Comment by shardnit** [comment]
:+1:

**Comment by kgish** [comment]
Sounds good to me as well.

**Comment by seancribbs** [comment]
For `PUT`, `resource_exists?` only determines whether condition validation is done or not.  If you would prefer only to accept the resource if it exists, the client should send `If-Match: *`, which will result in `412 Precondition Failed` IIRC. The semantics of `PUT` are literally "put this thing here", even if that URI does not represent something already existing.

**Comment by bethesque** [comment]
Have updated doco with a note in the PUT example, and a link to this issue. Thanks for the pointer @shardnit.

**Comment by shardnit** [comment]
Good that docs pointed to this issue. Its good to know the correct semantics of PUT, as @seancribbs raised, for handling non-existent resource.

**Comment by kgish** [comment]
Cool, thanks.
