### ISSUE TITLE
Cookie-based authentication

### ISSUE THREAD

**Issue by kgish** [seancribbs/webmachine-ruby#208]
I see that there's some documentation covering basic authentication but could not seem to discover any examples using cookie-based authentication.

Perhaps I'm not looking in the right places, can you help me perhaps?

**Comment by kgish** [comment]
Is there an example available explaining how to use session handling and token-based authentication using cookies?

**Comment by Asmod4n** [comment]
HTTP is per definition a session-less protocol and afaik webmachine only exposes what HTTP offers.
Doing session handling securely is hard, this looks like a opportunity to write a extension for webmachine?

I don't know if it should be a part of the core library.

@seancribbs @bethesque

**Comment by kgish** [comment]
Sure, I can give it a try.

**Comment by bethesque** [comment]
IMO, if there was boilerplate code that would be useful for someone else implementing the same thing, a separate gem would be the go. There's no guarantee that someone else wanting to implement session handling would want to use the same underlying technologies.

**Comment by bethesque** [comment]
Can we close this issue now?

**Comment by kgish** [comment]
Closed it.
