### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by kgish** [seancribbs/webmachine-ruby#210]
I want to add CORS support to my server by adding the following header to its response:
```
Access-Control-Allow-Origin: *
```
What's the best way to do this?

**Comment by Asmod4n** [comment]
create a finish_request callback for a resource and set the headers there: https://github.com/seancribbs/webmachine-ruby/blob/master/lib/webmachine/resource/callbacks.rb#L363
```ruby
response.headers['Access-Control-Allow-Origin'] = '*'
```

**Comment by bethesque** [comment]
Thought we should start a wiki page for all these little "how do I do ... with webmachine?" questions. https://github.com/seancribbs/webmachine-ruby/wiki/How-do-I-do-...-with-Webmachine%3F

**Comment by kgish** [comment]
Great idea, I'll see if I can add some creative ideas there.
