### ISSUE TITLE
undefined method `set_cookie'

### ISSUE THREAD

**Issue by kgish** [seancribbs/webmachine-ruby#212]
I am trying to set a cookie but the following exception is raised:
```
undefined method `set_cookie'
```
Here's what my code looks like, any ideas what I'm doing wrong?
```ruby
require 'resources/resource'
require 'models/user'
require 'json'

class SessionResource < Resource
   ...
  def content_types_accepted
    [['application/json', :create_session]]
  end
   ...
  def create_session
    ...
        if password == user.password
          response.set_cookie 'username', user.username
          ...
        end
  end
end
```
I've tried the following variations on the theme with no luck:
```
Webmachine::set_cookie
Webmachine::Resonse::set_cookie
set_cookie
```
Do I have to `require` or `include` something?

**Comment by seancribbs** [comment]
`@response.set_cookie` is there: https://github.com/seancribbs/webmachine-ruby/blob/master/lib/webmachine/response.rb#L47-L57

**Comment by seancribbs** [comment]
@kgish Was this just a result of using a really old version of the library in your project (like mentioned in the other issue)? If so, please close.
