### ISSUE TITLE
"ConnectionUnbound for an unknown signature: 21" in Travis CI

### ISSUE THREAD

**Issue by bethesque** [seancribbs/webmachine-ruby#215]
Anyone know anything about this? I've noticed it makes our Travis CI tests fail a fair bit. I've not done any EventMachine stuff before, so I have no idea.

```
 Failure/Error: @server_thread = Thread.new { @adapter.run }
     EventMachine::ConnectionNotBound:
       received ConnectionUnbound for an unknown signature: 21
```

**Comment by Asmod4n** [comment]
was a build_uri error i believe, at least the last couple runs with correct uris worked just fine, but we will see with more commits. (once i have checked and set uri.scheme and uri.port the error went away)

**Comment by bethesque** [comment]
Wow, unhelpful error message! Yay for green Travis!!! (I think that's the first time it's been green for a long time!)
