### ISSUE TITLE
Release 1.3.1?

### ISSUE THREAD

**Issue by bethesque** [seancribbs/webmachine-ruby#219]
Due to the REQUEST_URI bug, 1.3.0 fails all my tests*

https://travis-ci.org/bethesque/pact_broker/jobs/46823478

Can we release 1.3.1? My build is green against that.

_*_ Ok, a lot of my tests.

**Comment by seancribbs** [comment]
Yes please. I'll write up the release process this morning.

Sean Cribbs

**Comment by seancribbs** [comment]
@bethesque Will you do the honors? https://github.com/seancribbs/webmachine-ruby/wiki/Release-process

Ping me with any questions.

**Comment by bethesque** [comment]
On it.

**Comment by bethesque** [comment]
Released. Upgraded my project, all tests green, happy Beth.
