### ISSUE TITLE
Support webmachine being mapped inside a parent rack app

### ISSUE THREAD

**Issue by madlep** [seancribbs/webmachine-ruby#222]
I'm considering submitting a PR to add support for webmachine to work when added to a parent rack app with `Rack::Builder#map` (and therefore`ActionDispatch::Routing::Mapper::Base#mount` in Rails, as it uses the same semantics).

I can see technically how to make it work, but I'm wondering if this is something that fits with the philosophy/direction of webmachine development, and whether it's worth pursuing?

My intended use case is mounting in a parent Rails app as an API endpoint. The code in the webmachine app needs access to shared application code and ActiveRecord models, but doesn't rely on the any URLs or HTTP handling etc from the rest of the app. It's not feasible to mount it at the root URL. I can route webmachine resources by prefixing all the full URL components, but that feels messy and fragile.

Summary of proposed changes 
- `Webmachine::Request` would contain an optional `parsed_tokens` attribute
- `Webmachine::Adapters::Rack` would then build `parsed_tokens` by parsing `env["PATH_INFO"]`, rather than relying on the URL reconstructed by `Rack::Request` and pass it to the `Webmachine::Request` instance when it is created (as well as the URL)
- routing would use the `parsed_tokens` on the request if available. If not, routing would parse the tokens on it's own as it does now. This preserves backward compatibility with other adapters in webmachine, and that may have been implemented elsewhere in the community.
- URL is still passed through the request handling and decision tree as it currently does, and logic works the same aside form choosing the initial resource to route to.

Consider a toy rack app with a webmachine app added with `map`:

```ruby
#config.ru
require 'webmachine'
require 'webmachine/adapters/rack'

MyWebmachineApp = Webmachine::Application.new do |app|
  class ItemsResource < Webmachine::Resource
    def to_html
      "here's your item with id #{request.path_info[:item_id]} disp_path=#{request.disp_path}"
    end
  end

  class WrongResource < Webmachine::Resource
    def to_html
      "BZZZTT. Shouldn't have gotten here. disp_path=#{request.disp_path}"
    end
  end

  app.routes do
    # SHOULD match if we used env["PATH_INFO"], but it doesn't
    add ["items", :item_id], ItemsResource

    # ACTUALLY matches, due to matching on tokens from original full URL
    add ["webmachine", "items", :item_id], WrongResource
  end

  app.configure do |config|
    config.adapter = :Rack
  end
end

map '/' do
  run lambda{|env| [200, {"Content-Type" => "text/html"}, ["WINNING AT THE INTERNET!"]] }

  map '/webmachine' do
    run MyWebmachineApp.adapter
  end
end
```

if we start it up with `rackup config.ru`, then send a request to `http://localhost:9292/webmachine/items/123`, I would want to get back a response from the `ItemsResource`,  but instead it is routed to the `WrongResource`.

This is due to webmachine routing using the full URL rather than just the rack `path_info` parameter.

With my proposed change, it would work as expected. Using `env["PATH_INFO"]` rather than the full URL is how other rack applications such as Sinatra etc handle being mounted at a point in a parent application.

Hope this makes sense. Would love any feedback on the idea.

**Comment by bethesque** [comment]
I would quite like this feature as the current functionality has been an annoyance to me in building composable web applications with Rack. I think this is a pity because it's one of Rack's strong points, and I love both Webmachine and Rack. I would like to see this feature, though I understand if the original Webmachine authors feel that it is not in line with the Webmachine architectural philosophy. 

Perhaps, rather than modifying the current Rack adapter, a separate one could be created with this explicit functionality? I don't quite see how backwards compatibility could be maintained without some modification to the code that sets up the composed application.

**Comment by seancribbs** [comment]
When I ported it I wasn't entirely sure of the purpose, but we should be able to set `base_uri` on the `Request` to accomplish this. All of the interactions with that parameter will need to be examined, however.

Does / can Rack pass the appropriate information along so we can set it?

**Comment by madlep** [comment]
@bethesque - yeah, you're right. Particularly if any webmachine apps were already being hosted with a rack map setup, they would break if the changes were made on the main rack adapter. A separate one makes sense to preserve backward compatibility in that case.

@seancribbs not sure I follow about `base_uri`. It just looks like it's used for setting the `Location` for redirects by the look of it during resource decision processing. Not sure how to implement this feature using that as you suggest. The part of the URI that is NOT the `base_uri` is what is required for routing - and it's required prior to resource handling.

However, thanks for pointing that out! I'd missed that one. That value does need to be explicitly set for a rack mapped app to include the location where the app is mapped at as part of the base. At the moment it's just setting it to the uri discarding the query string and path e.g. "http://example.com/". For mapped apps, it would need to be set to something like "http://example.com/parent/mapped/path" instead.

**Comment by madlep** [comment]
Anyway, I opened a PR at https://github.com/seancribbs/webmachine-ruby/pull/223

haven't implemented setting the correct `base_uri` change for mapped apps yet.
