### ISSUE TITLE
Enumerator.new deprecation warning

### ISSUE THREAD

**Issue by kylekyle** [seancribbs/webmachine-ruby#224]
When using webmachine-sprockets, I get the following warning for every asset served:

```
webmachine-sprockets-0.2.0/lib/webmachine/sprockets/resource.rb:18: warning: Enumerator.new without a block is deprecated; use Object#to_enum
```

**Comment by bethesque** [comment]
Should that be an issue in https://github.com/lgierth/webmachine-sprockets then?

**Comment by seancribbs** [comment]
Yes, it should.

**Comment by kylekyle** [comment]
Whoops! Yep. It sure should. Sorry about that!
